### PR TITLE
Fix command builder

### LINKED ISSUE #881: Can't add parameter to Command
**Environment**
- PHP Version:
    - 8.0.21
- DiscordPHP Version:
    - dev-master

**Describe the bug**
```
Fatal error: Uncaught Error: Typed property Discord\Builders\CommandBuilder::$options must not be accessed before initialization in C:\Users\Sanders\Documents\Projects\discord-bot\vendor\team-reflex\discord-php\src\Discord\Builders\CommandAttributes.php:220
Stack trace:
#0 ...\discord-bot\bot.php(40): Discord\Builders\CommandBuilder->addOption(Object(Discord\Parts\Interactions\Command\Option))
#1 ...\discord-bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): {closure}(Object(Discord\Discord))
#2 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(1086): Discord\Discord->emit('ready', Array)
#3 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(945): Discord\Discord->ready()
#4 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(481): Discord\Discord->setupChunking()
#5 ...\discord-bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): Discord\Discord->Discord\{closure}(Object(Discord\Parts\Guild\Guild), Object(Discord\Discord), NULL)
#6 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(741): Discord\Discord->emit('GUILD_CREATE', Array)
#7 ...\discord-bot\vendor\react\promise\src\FulfilledPromise.php(42): Discord\Discord->Discord\{closure}(Object(Discord\Parts\Guild\Guild))
#8 ...\discord-bot\vendor\react\promise\src\Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#9 ...\discord-bot\vendor\react\promise\src\Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#10 ...\discord-bot\vendor\react\promise\src\Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#11 ...\discord-bot\vendor\react\promise\src\Deferred.php(36): React\Promise\Promise::React\Promise\{closure}(Object(Discord\Parts\Guild\Guild))
#12 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\WebSockets\Events\GuildCreate.php(136): React\Promise\Deferred->resolve(Object(Discord\Parts\Guild\Guild))
#13 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\WebSockets\Events\GuildCreate.php(166): Discord\WebSockets\Events\GuildCreate->Discord\WebSockets\Events\{closure}()
#14 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(765): Discord\WebSockets\Events\GuildCreate->handle(Object(Discord\Helpers\Deferred), Object(stdClass))
#15 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(630): Discord\Discord->handleDispatch(Object(stdClass))
#16 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(599): Discord\Discord->processWsMessage(Object(stdClass))
#17 ...\discord-bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): Discord\Discord->handleWsMessage(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\Client\WebSocket))
#18 ...\discord-bot\vendor\ratchet\pawl\src\WebSocket.php(72): Ratchet\Client\WebSocket->emit('message', Array)
#19 ...\discord-bot\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\RFC6455\Messaging\MessageBuffer))
#20 ...\discord-bot\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData('\x82~+\x08x\x9C\xED]{\x93\xDB\xD6u\xFF*...')
#21 ...\discord-bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData('\x82~+\x08x\x9C\xED]{\x93\xDB\xD6u\xFF*...')
#22 ...\discord-bot\vendor\react\stream\src\Util.php(71): Evenement\EventEmitter->emit('data', Array)
#23 ...\discord-bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('\xAF\xBF\x9B(G\xF8n\x82\xFC\x0F\x0F\x02\xD7\x19\xAE...')
#24 ...\discord-bot\vendor\react\stream\src\DuplexResourceStream.php(196): Evenement\EventEmitter->emit('data', Array)
#25 ...\discord-bot\vendor\react\event-loop\src\StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData(Resource id #189)
#26 ...\discord-bot\vendor\react\event-loop\src\StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity(4295224)
#27 ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(1423): React\EventLoop\StreamSelectLoop->run()
#28 ...\discord-bot\bot.php(85): Discord\Discord->run()
#29 {main}
  thrown in ...\discord-bot\vendor\team-reflex\discord-php\src\Discord\Builders\CommandAttributes.php on line 220

Process finished with exit code 255
```

**To Reproduce**
```php
$builder = CommandBuilder::new()->setName('muteuser')
        ->setDescription('test');

    $builder->addOption(
        (new \Discord\Parts\Interactions\Command\Option($discord))
            ->setName('user')
            ->setDescription('User'));

    $command = new Command($discord, $builder->toArray());

    $discord->application->commands->save($command);
```
I thought this should add parameters to the slash command, however this throws the said error

### PR DESCRIPTION
**Pull request by SQKo**
Fixes #881 

Tested

### CODE REVIEW

**Comment by SQKo** [comment]
Also fix #879 again, but the empty check becomes useless now

**Review by key2peace — DISMISSED** [review]

File: src/Discord/Builders/CommandAttributes.php [hunk 1]
```diff
@@ -241,7 +241,7 @@ public function removeOption(Option $option): self
             throw new \DomainException('Only CHAT_INPUT Command type can have option.');
         }
 
-        if (($idx = array_search($option, $this->option)) !== null) {
+        if (isset($this->options) && ($idx = array_search($option, $this->options)) !== null) {
```
Comment (key2peace) [inline src/Discord/Builders/CommandAttributes.php:244]: shouldn't that be ``false`` instead of ``null`` ?
as per array_search docs (https://www.php.net/manual/en/function.array-search.php#refsect1-function.array-search-returnvalues)

**Review by key2peace — APPROVED** [review]
