### PR TITLE
Fix most of event cache data inconsistency, variables naming, and add docs link

### LINKED ISSUE #714: joined_at is always null when using loadallmembers
**Environment**
- PHP Version:
    - 8.1.2
- DiscordPHP Version:
    - dev-master

**Describe the bug**
Everytime when you use `$member->joined_at` it is null

**To Reproduce**
```php
$discord->on(Event::GUILD_MEMBER_REMOVE, function (Member $member, Discord $discord) {
    $logchannel = $discord->getChannel("<channel id>");
    $logchannel->sendMessage("joined_at: {$member->joined_at}");
});
```

**Expected behavior**
Get the join date of the member

### PR DESCRIPTION
**Pull request by SQKo**
Follow up to #711 but for old & existing events

Fixes #714 (only if member is cached)

I will also check for other events

### CODE REVIEW

File: src/Discord/WebSockets/Events/GuildMemberRemove.php [hunk 1]
```diff
@@ -22,13 +22,17 @@ class GuildMemberRemove extends Event
...
+        if ($guild = $this->discord->guilds->get('id', $data->guild_id)) {
+            $member = $guild->members->pull($data->user->id);
             --$guild->member_count;
+        }
 
-            $this->discord->guilds->push($guild);
+        if (! $member) {
+            /** @var Member */
+            $member = $this->factory->create(Member::class, $data, true);
+            $member->guild_id = $data->guild_id;
```
Comment (SQKo) [inline src/Discord/WebSockets/Events/GuildMemberRemove.php:35]: Due to GUILD_MEMBER_REMOVE actually only returns an `User`, instead of `Member`, this should be replaced in next major version update.

The question here is whether to attach `guild_id` or not since the member is already removed.

**Comment by SQKo** [comment]
Also follow up to #694 for `MESSAGE_CREATE` event only

**Review by valzargaming — APPROVED** [review]

**Review by valzargaming — APPROVED** [review]

**Comment by SQKo** [comment]
There was a little mistake with GuildBanRemove, everything else has been tested, so it can be merged right away.

**Review by key2peace — APPROVED** [review]
