### PR TITLE
Fix variable name mistaken when resolving PR conflict

### LINKED ISSUE #851: Undefined variable: user
I just update to lasted version of DiscordPHP and it's look like there is misstype for variable in 
**Repository/Guild/BanRepository.php**  https://github.com/discord-php/DiscordPHP/tree/master/src/Discord/Repository/Guild over here you can see it aswell it should be $member instant of $user it is on line 108 
```
        if ($user instanceof User || $user instanceof Member) {

```

### PR DESCRIPTION
**Pull request by SQKo**
Was a mistake when resolving conflict from https://github.com/discord-php/DiscordPHP/pull/840/commits/ad14bc3827753bc8299973dd5927c6b6811580c3

Fixes #851

### CODE REVIEW

**Review by valzargaming — APPROVED** [review]

File: src/Discord/Repository/Guild/BanRepository.php [hunk 1]
```diff
@@ -103,14 +103,14 @@ public function ban($member, ?int $daysToDeleteMessages = null, ?string $reason
...
      * @return ExtendedPromiseInterface
      */
-    public function unban($member, ?string $reason = null): ExtendedPromiseInterface
+    public function unban($user, ?string $reason = null): ExtendedPromiseInterface
     {
         if ($user instanceof User || $user instanceof Member) {
             $user = $user->id;
         } elseif ($user instanceof Ban) {
             $user = $user->user_id;
         }
```
Comment (SQKo) [inline src/Discord/Repository/Guild/BanRepository.php:112]: Seems not necessary to check since `delete()` will take the `Ban` Part

File: src/Discord/Repository/Guild/BanRepository.php [hunk 2]
```diff
@@ -103,14 +103,14 @@ public function ban($member, ?int $daysToDeleteMessages = null, ?string $reason
      *
      * @return ExtendedPromiseInterface
      */
-    public function unban($member, ?string $reason = null): ExtendedPromiseInterface
+    public function unban($user, ?string $reason = null): ExtendedPromiseInterface
     {
         if ($user instanceof User || $user instanceof Member) {
             $user = $user->id;
         } elseif ($user instanceof Ban) {
             $user = $user->user_id;
```
Comment (SQKo) [inline src/Discord/Repository/Guild/BanRepository.php:111]: Seems not necessary to check since `delete()` will take the `Ban` Part
